const ERROR_MESSAGES = {
  VM_CONFIG_INIT: "Component setup initiated for Scenario.",
  VM_CONFIG_SUCCESS: "Set Configurations Successfully.",
  CONFIG_NOT_FOUND: "Component configuration not found.",
  PROXMOX_FAILURE: "Error generating the access token,please try after some time.",
  CONFIG_NOT_FOUND_SCENARIO: "Component configuration not found of scenario.",
  LEARNER_NOT_FOUND: "Learner data not found.",
  NETWORK_BRIDGES: "Not enough available network bridges.",
  COMPONENT_NOT_FOUND: "Component configuration is invalid in scenario.",
  COM_TYPE_NOT_FOUND: "Component Type not found.",
  PREVIOUS_NETWORK: "Failed to resolve previously assigned network bridge.",
  NO_COMPONENTS_FOR_STATUS: "No components found for the given status.",
  MISSING_TARGET_VMID: "Component is missing target VMID.",
  MISSING_MASTER_VMID: "Component is missing master VMID.",
  CLONE_FAILED: "Clone failed for component.",
  CONFIGURATION_FAILED: "Configuration failed for component.",
  START_FAILED: "Start failed for component.",
  CONFIGURATION_ERROR: "Error during component configuration.",
  START_ERROR: "Error during VM start.",
  STOP_ERROR: "Error during VM stop.",
  DESTROY_ERROR: "Error during VM destroy.",
  UNHANDLED_SETUP_ERROR: "Unhandled error during component setup.",
  UNHANDLED_CONFIGURE_ERROR: "Unhandled error during component configuration.",
  UNHANDLED_START_ERROR: "Unhandled error during component start.",
  FAILURE_MARKED: "Marking all components and session as 'Failed'.",
  CONFIG_SUCCESS: "Set Configurations Successfully.",
   COMPONENT_OPERATION_FAILED: "Failed to stop or destroy one or more components during cleanup.",
  CLEANUP_COMPLETED_WITH_FAILURE: "All applicable components were stopped and destroyed, but marked as failed as part of cleanup.",
};
module.exports = ERROR_MESSAGES;
