const dashboardRouter = require("../components/dashboard");
const profileRouter = require("../components/profile");
const scenarioRouter = require("../components/scenarios");
const customscenariosRouter = require("../components/custom_scenarios");
const vmconfigsRouter = require("../components/vmconfigs");
const eventlearnerRouter = require("../components/eventlearner");
const chatBoxRouter = require("../components/chatbox");
const scenarioQuizRouter = require("../components/scenario_quiz");
const faqsRouter = require("../components/faqs");
const eventsRouter = require("../components/events");
const eventChatBoxRouter = require("../components/eventchatbox");
const notificationRouter = require("../components/notification");
const authRouter = require("../components/auth");
const commonRouter = require("../components/commons");

module.exports = function (iocContainer) {
  const { express, authJwt } = iocContainer;
  const router = express.Router();
  router.use("/auth", authRouter(iocContainer));
  router.use("/vmconfigs",vmconfigsRouter(iocContainer));
  router.use("/dashboard", authJwt.authenticateToken, dashboardRouter(iocContainer));
  router.use("/profile", authJwt.authenticateToken, profileRouter(iocContainer));
  router.use("/scenarios", authJwt.authenticateToken, scenarioRouter(iocContainer));
  router.use("/custom_scenarios", authJwt.authenticateToken, customscenariosRouter(iocContainer));
  router.use("/eventlearner", authJwt.authenticateToken, eventlearnerRouter(iocContainer));
  router.use("/chatbox", authJwt.authenticateToken, chatBoxRouter(iocContainer));
  router.use("/scenario_quiz", authJwt.authenticateToken, scenarioQuizRouter(iocContainer));
  router.use("/faqs", authJwt.authenticateToken, faqsRouter(iocContainer));
  router.use("/events", authJwt.authenticateToken, eventsRouter(iocContainer));
  router.use("/eventchatbox", authJwt.authenticateToken, eventChatBoxRouter(iocContainer));
  router.use("/notification", authJwt.authenticateToken, notificationRouter(iocContainer));
  router.use("/commons", authJwt.authenticateToken, commonRouter(iocContainer));
  return router;
};